//HintName: Injectables.g.cs
// <auto-generated />
using System;
using System.Collections.Generic;
using System.Linq;
using Injectable;
using Injectable.Abstractions;
using Microsoft.Extensions.DependencyInjection;

namespace Injectable
{
    public static partial class Injectables
    {
        private static readonly System.Collections.Generic.HashSet<string> RequestedNamespaces = new(System.StringComparer.Ordinal);

        public static void AddNamespace(string @namespace)
        {
            if (string.IsNullOrWhiteSpace(@namespace))
            {
                return;
            }

            RequestedNamespaces.Add(@namespace);
        }

        public static System.Collections.Generic.IReadOnlyCollection<string> GetRequestedNamespaces() => RequestedNamespaces;

        public static IEnumerable<InjectableType> GetInjectables()
        {
            yield return new InjectableType
            {
                Service = typeof(<global namespace>.IInjectableInterface),
                Implementation = typeof(<global namespace>.MyInjectableClass),
                Attribute = new InjectAttribute(InjectionType.Decorated, ServiceLifetime.Singleton)
            };

        }
    }
}